remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-toc

baseurl: ""
url: "https://NatuLe.github.io" # the base hostname & protocol for your site


toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: 'no_toc_section'
  list_type: 'ul'
