remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  
baseurl: ""
url: "https://NatuLe.github.io" # the base hostname & protocol for your site


markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: false
mathjax:
  enable: true
